apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "flyte-sandbox.persistence.minioVolumeName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/var/lib/flyte/storage/minio"
