{{- if .Values.configuration.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flyte-binary.configuration.auth.adminAuthSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
type: Opaque
{{- end }}
