{{- if .Values.sandbox.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-sandbox.fullname" . }}-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    {{- include "flyte-sandbox.proxySelectorLabels" . | nindent 4 }}
{{- end }}
