{{- if .Values.flyteagent.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-binary.agent.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.flyteagent.deployment.labels }}
    {{- tpl ( .Values.flyteagent.deployment.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.flyteagent.deployment.annotations }}
    {{- tpl ( .Values.flyteagent.deployment.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.flyteagent.deployment.replicas }}
  selector:
    matchLabels: {{- include "flyte-binary.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "flyte-binary.agent.selectorLabels" . | nindent 8 }}
        {{- if .Values.commonLabels }}
        {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 8 }}
        {{- end }}
        {{- if .Values.flyteagent.deployment.podLabels }}
        {{- tpl ( .Values.flyteagent.deployment.podLabels | toYaml ) . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.commonAnnotations }}
        {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 8 }}
        {{- end }}
        {{- if .Values.flyteagent.deployment.podAnnotations }}
        {{- tpl ( .Values.flyteagent.deployment.podAnnotations | toYaml ) . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.flyteagent.deployment.extraPodSpec }}
      {{- tpl ( .Values.flyteagent.deployment.extraPodSpec | toYaml ) . | nindent 6 }}
      {{- end }}
      {{- if .Values.flyteagent.deployment.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.flyteagent.deployment.podSecurityContext "enabled" | toYaml | nindent 12 }}
      {{- end }}
      serviceAccountName: {{ include "flyte-binary.agent.serviceAccountName" . }}
      {{- if .Values.flyteagent.deployment.initContainers }}
      initContainers:
      {{- tpl ( .Values.flyteagent.deployment.initContainers | toYaml ) . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          {{- with .Values.flyteagent.deployment.image }}
          image: {{ printf "%s:%s" .repository .tag | quote }}
          imagePullPolicy: {{ .pullPolicy | quote }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.command }}
          command: {{- tpl ( .Values.flyteagent.deployment.command | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.args }}
          args:
          {{- tpl ( .Values.flyteagent.deployment.args | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.extraEnvVars }}
          env:
          {{- tpl ( .Values.flyteagent.deployment.extraEnvVars | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if or .Values.flyteagent.deployment.extraEnvVarsConfigMap .Values.flyteagent.deployment.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.flyteagent.deployment.extraEnvVarsConfigMap }}
            - configMapRef:
                name: {{ .Values.flyteagent.deployment.extraEnvVarsConfigMap }}
            {{- end }}
            {{- if .Values.flyteagent.deployment.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.flyteagent.deployment.extraEnvVarsSecret }}
            {{- end }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: 8000
          {{- if .Values.flyteagent.deployment.startupProbe }}
          startupProbe: {{- tpl ( .Values.flyteagent.deployment.startupProbe | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.livenessProbe }}
          livenessProbe:
          {{- tpl ( .Values.flyteagent.deployment.livenessProbe | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.readinessProbe }}
          readinessProbe:
          {{- tpl ( .Values.flyteagent.deployment.readinessProbe | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.resources }}
          resources: {{- toYaml .Values.flyteagent.deployment.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.lifecycleHooks }}
          lifecycle: {{- tpl ( .Values.flyteagent.deployment.lifecycleHooks | toYaml ) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flyteagent.deployment.extraVolumeMounts }}
          volumeMounts:
          {{- tpl ( .Values.flyteagent.deployment.extraVolumeMounts | toYaml ) . | nindent 12 }}
          {{- end }}
        {{- if .Values.flyteagent.deployment.sidecars }}
        {{- tpl ( .Values.flyteagent.deployment.sidecars | toYaml ) . | nindent 8 }}
        {{- end }}
      {{- if .Values.flyteagent.deployment.extraVolumes }}
      volumes:
      {{- tpl ( .Values.flyteagent.deployment.extraVolumes | toYaml ) . | nindent 8 }}
      {{- end }}
{{- end }}
