{{- if .Values.flyteagent.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-binary.agent.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.flyteagent.service.labels }}
    {{- tpl ( .Values.flyteagent.service.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.flyteagent.service.annotations }}
    {{- tpl ( .Values.flyteagent.service.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.flyteagent.service.type }}
  {{- if or (eq .Values.flyteagent.service.type "LoadBalancer") (eq .Values.flyteagent.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.flyteagent.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.flyteagent.service.type "LoadBalancer") (not (empty .Values.flyteagent.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.flyteagent.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.flyteagent.service.type "LoadBalancer") (not (empty .Values.flyteagent.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.flyteagent.service.loadBalancerIP }}
  {{- end }}
  {{- if and .Values.flyteagent.service.clusterIP (eq .Values.flyteagent.service.type "ClusterIP") }}
  clusterIP: {{ .Values.flyteagent.service.clusterIP }}
  {{- end }}
  ports:
    - name: grpc
      port: {{ include "flyte-binary.agent.servicePort" . }}
      targetPort: grpc
      {{- if and (or (eq .Values.flyteagent.service.type "NodePort") (eq .Values.flyteagent.service.type "LoadBalancer")) (not (empty .Values.flyteagent.service.nodePort)) }}
      nodePort: {{ .Values.flyteagent.service.nodePort }}
      {{- else if eq .Values.flyteagent.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.flyteagent.service.extraPorts }}
    {{- tpl ( .Values.flyteagent.service.extraPorts | toYaml ) . | nindent 4 }}
    {{- end }}
  selector: {{- include "flyte-binary.agent.selectorLabels" . | nindent 4 }}
{{- end }}
