{{- if .Values.flyteagent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "flyteagent.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteagent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flyteagent.replicaCount }}
  selector:
    matchLabels: {{ include "flyteagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.flyteagent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{ include "flyteagent.labels" . | nindent 8 }}
    spec:
      {{- if .Values.flyteagent.priorityClassName }}
      priorityClassName: {{ .Values.flyteagent.priorityClassName }}
      {{- end }}
      containers:
      - command:
        - pyflyte
        - serve
        image: "{{ .Values.flyteagent.image.repository }}:{{ .Values.flyteagent.image.tag }}"
        imagePullPolicy: "{{ .Values.flyteagent.image.pullPolicy }}"
        name: flyteagent
        ports:
        - containerPort: {{ .Values.flyteagent.ports.containerPort }}
          name: {{ .Values.flyteagent.ports.name }}
        resources: {{- toYaml .Values.flyteagent.resources | nindent 10 }}
        {{- with .Values.flyteagent.additionalVolumeMounts -}}
        {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.flyteagent.additionalContainers -}}
      {{- tpl (toYaml .) $ | nindent 6}}
      {{- end }}
      serviceAccountName: {{ template "flyteagent.name" . }}
      {{- with .Values.flyteagent.additionalVolumes -}}
      {{ tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with .Values.flyteagent.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.flyteagent.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.flyteagent.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}
