name: release

on:
  push:
    tags:
      - abc/v*.*.* # stable release like, v0.19.2

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: test1
        run: |
          echo ${GITHUB_REF#refs/tags/}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          args: release --rm-dist

