name: release

on:
  push:
    tags:
      - abc/v*.*.* # stable release like, v0.19.2

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: test1
        run: |
          echo ${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          args: release --rm-dist -f f/.goreleaser.yml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
