name: Flytectl-specific checks

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - flytectl/**
  push:
    branches:
      - master

jobs:
  install-script:
    name: Install script
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - v0.8.20
          - latest
          # Test the case where no version is specified
          - " "
    steps:
      - uses: actions/checkout@v4
      - uses: nick-fields/retry@v3
        with:
          timeout_seconds: 15
          max_attempts: 3
          command: chmod +x ./flytectl/install.sh && ./flytectl/install.sh ${{ matrix.version }} && ./bin/flytectl version

