name: Run unit tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
env:
  GO_VERSION: "1.19"
  PRIORITIES": "P0"
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        component:
          [
            datacatalog,
            flyteadmin,
            flytecopilot,
            flyteplugins,
            flytepropeller,
            flytestdlib,
          ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.component }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v3.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: false
